# Last edited on 2010-05-22 21:58:49 by stolfi

PROG := make_test_classif_data

JS_LIBS := \
  libclassif.a \
  libimg.a \
  libgeo.a \
  libjs.a

all: build install

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

