#Last edited on 2012-12-22 20:39:14 by stolfilocal

PROG := compute_decim_weights
PROGDIR := ..

include ${STOLFIHOME}/programs/c/GENERIC-PROGS-TEST.make

all: ${PROGDIR}/${PROG}
	${PROGDIR}/${PROG}
        
