# Last edited on 2013-07-26 20:51:18 by stolfilocal

PROG := eratos64
PROGDIR := ..


all: run

include ${STOLFIHOME}/programs/c/GENERIC-PROGS-TEST.make

run: ${PROGDIR}/${PROG}
	${PROGDIR}/${PROG} 100 200
	${PROGDIR}/${PROG} 1000 2000
	${PROGDIR}/${PROG} 100000000 200000000
