#! /bin/bash 
# Last edited on 2005-08-20 18:53:02 by stolfi

cmd=${0##*/}
usage="${cmd} [-show [-timeout NSECS]] NAME TMIN TMAX"

# Plots the approximate and true solutions for {SPTimeOnlySolveG3C1}. 

function error()
{ 
  echo "${cmd}: $1" >&2; 
  echo "usage: ${usage}" >&2; 
  exit 1;
}

show=0
timeout=0
while [ $# -gt 0 ]; do
  case "$1" in
    -show ) 
      show=1; shift ;;
    -timeout ) 
      timeout="$2"; shift; shift ;;
    -* )
      error "unrecognized option $1"; exit 1 ;;
    * ) break;;
  esac;
done

if [ $# -ne 3 ]; then
  error "wrong number of parameters"; 
fi

name="$1"; shift;
tmin="$1"; shift;
tmax="$1"; shift;

pltfile="${name}.plt"
valepsfile="${name}-val.eps"
difepsfile="${name}-dif.eps"
resepsfile="${name}-res.eps"

# Create gnuplot script:
gnuplot <<EOF
set term postscript eps color "TimesRoman" 18
set size 2,1
tmin=${tmin}
tmax=${tmax}
tdel=(tmax-tmin)
set title "${name}"
set xlabel "t"
set ylabel "sol"
set key top right
set xrange [(tmin-0.05*tdel):(tmax+0.05*tdel)]
set xtics 1
set yzeroaxis
set xzeroaxis
set output "${valepsfile}"
set yrange [-2.0:+2.0]
plot \
  "${pltfile}" using 1:2 title "app(t)" with linespoints lt 1 pt 6, \
  "${pltfile}" using 1:8 title "sol(t)" with linespoints lt 3 pt 6, \
  "${pltfile}" using 1:9 title "err(t)" with linespoints lt 0 pt 6

set output "${difepsfile}"
set yrange [-3.0:+3.0]
plot \
  "${pltfile}" using 1:2 title "app(t)" with linespoints lt 1 pt 6, \
  "${pltfile}" using 1:3 title "TD(app(t))" with linespoints lt 7 pt 1, \
  "${pltfile}" using 1:4 title "TDD(app(t))" with linespoints lt 0 pt 2

set output "${resepsfile}"
set yrange [-2.0:+2.0]
plot \
  "${pltfile}" using 1:5 title "L(app)(t)" with linespoints lt 3 pt 6, \
  "${pltfile}" using 1:6 title "rhs(app(t),t)" with linespoints lt 7 pt 7, \
  "${pltfile}" using 1:7 title "L(app)-rhs" with linespoints lt 0 pt 8
quit
EOF

if [ ${show} -ne 0 ]; then
  show-eps -timeout ${timeout} ${valepsfile} &
  show-eps -timeout ${timeout} ${difepsfile} &
  show-eps -timeout ${timeout} ${resepsfile}
fi
