# Makefile for generic C program
# Last edited on 2023-02-03 23:22:39 by stolfi

PROGS := \
  quadwfc \
  plotwfc \
  povwfc

JS_LIBS := \
  libgeo.a \
  libquad.a \
  libeps.a \
  libimg.a \
  libjs.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
