# Last edited on 2009-02-10 08:35:40 by stolfi

all:
	@echo "*** make all: Modula-3 subdirectory"

build:
	@echo "*** make build: Modula-3 subdirectory"

clean::
	@echo "*** make clean: Modula-3 subdirectory"

install:
	@echo "*** make install: Modula-3 subdirectory"

uninstall:
	@echo "*** make uninstall: Modula-3 subdirectory"
