# Last edited on 2023-02-03 23:23:08 by stolfi
# Makefile for pnmfit

PROG = demography

JS_LIBS = \
  libstreetmap.a \
  libimg.a \
  libeps.a \
  libquad.a \
  libgeo.a \
  libjs.a
 
include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
