# Last edited on 2015-12-01 16:25:10 by stolfilocal

PROGS := \
  gch_giftwrap \
  gch_point_generator \
  gch_point_generator_sphere \
  gch_pov_generator \
  gch_point_proj_hc

JS_LIBS := \
  libgem.a \
  libgeo.a \
  libjs.a

OTHER_LIBS := \
  /lib64/libgmp.so

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
