# Last edited on 2023-06-27 11:53:13 by stolfi

PROGS := \
  gdr_test_demo \
  gdr_test_gen_children \
  gdr_test_sim \
  gdr_test_draw \
  gdr_main

NON_PROGS :=
  
JS_LIBS := \
  libdrtree.a \
  libimg.a \
  libeps.a\
  libgeo.a \
  libjs.a
  
IGNORE := \
  gdr_main.c
       
include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
