# Last edited on 2019-12-16 12:33:24 by jstolfi

PROG := gauss_tripart_opt

IGNORE := \
  junk.c

JS_LIBS := \
  libminn.a \
  liblsq.a \
  libgeo.a \
  libjs.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
