# Makefile for generic C program
# Last edited on 2009-02-10 11:35:19 by stolfi

PROGS := \
  tsp_sph_vol \
  tsp_enum
  
JS_LIBS := \
  libminu.a \
  libjs.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

