# Last edited on 2022-04-20 00:24:45 by stolfi
# Last edited on 2019-05-28 16:28:36 by jstolfi

# TESTNAME := test
# TESTNAME := BC_walls
# TESTNAME := drawers_CC1
# TESTNAME := BC_drawers
# TESTNAME := BC_drawer_sides
# TESTNAME := CC
TESTNAME := TTH

all: 
	${MAKE} -f ${TESTNAME}.make
        
