# Last edited on 2010-08-15 00:57:34 by stolfi

# Needs to be checked and cleaned up. There is a newer version somewhere!!!

PROG := taa 

USE_X11 := YES

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
