# Last edited on 2023-02-03 23:22:20 by stolfi

PROGS := \
  tmaze_test \
  tmaze_stats \
  tmaze_figs

JS_LIBS := \
  libdgraph.a \
  libspmat.a \
  libeps.a \
  libjs.a
  
OTHER_C_FLAGS := -dD

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
