# Last edited on 2023-02-03 23:23:04 by stolfi

PROG := optimize

JS_LIBS := \
  libstreetmap.a \
  libeps.a \
  libquad.a \
  libgeo.a \
  libjs.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

