# Last edited on 2012-12-15 23:25:48 by stolfilocal

PROG := logmrgck
PROGDIR := ../..

all: run

include ${STOLFIHOME}/programs/c/GENERIC-PROGS-TEST.make

run: ${PROGDIR}/${PROG}
	${PROGDIR}/${PROG}
