# Last edited on 2015-04-20 18:10:41 by stolfilocal

PROG := fit_btc_bubble_model

JS_LIBS := \
  libbtc.a \
  libminn.a \
  liblsq.a \
  libgeo.a \
  libjs.a

all: build install

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

