# Last edited on 2009-02-10 12:02:35 by stolfi

# Needs to be checked and cleaned up. There is a newer version somewhere!!!

PROGS := \
  ga \
  ifs \
  ifsga \
  ifsi

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
