# Last edited on 2020-01-15 11:05:36 by jstolfi

PROG := gauss_series_error_map

IGNORE := \
  junk.c

JS_LIBS := \
  libminn.a \
  liblsq.a \
  libgeo.a \
  libjs.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
