# Last edited on 2023-02-03 23:22:59 by stolfi
# Makefile for pnmfit

PROG = plotmap

JS_LIBS = \
  libstreetmap.a \
  libeps.a \
  libquad.a \
  libgeo.a \
  libjs.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

