# Last edited on 2020-10-27 15:16:08 by jstolfi

PROG := choose_sheet_cuts

JS_LIBS := \
  libsheetcut.a \
  libeps.a \
  libgeo.a \
  libjs.a

OTHER_LIBS :=

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
