#Last edited on 2013-01-11 12:27:38 by stolfilocal

PROG := test_gen_derangement
PROGDIR := ..

include ${STOLFIHOME}/programs/c/GENERIC-PROGS-TEST.make

all: ${PROGDIR}/${PROG}
	${PROGDIR}/${PROG}
        
