# Last edited on 2023-02-03 23:23:12 by stolfi

PROG := irt_main

JS_LIBS := \
  libeps.a \
  libgeo.a \
  libzf.a \
  libaa.a \
  libia.a \
  libflt.a \
  libimg.a \
  libjs.a

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

all: build
