# -*- makefile -*-
# $Id: Makefile,v 1.7 1997/06/19 19:09:58 pmartin Exp $

BFS_FLAGS := -DNO_ERROR_HANDLING -DSTATS -DCONCISE
CXXFLAGS += ${BFS_FLAGS}

BINARIES = bim_bfs

MAIN = bfs_run.cc

# pick options for the binaries
bim_bfs_opts= -DBDFS

include ../../make.config

